### ISSUE TITLE
Add command to show queue

### ISSUE THREAD

**Issue by Tams-Tams** [Ginger-Industries/GingerBot#6] opened 2022-01-22 21:19 UTC
Add a command like `show` to show the not-yet pushed queue.

**Comment by GingerIndustries** [comment] 2022-01-23 15:23
Duplicate of [Issue 3](https://github.com/Ginger-Industries/GingerBot/issues/3). Leave a comment if you want to work on this issue.

**Closed by GingerIndustries** 2022-01-23 15:23 UTC
